config/routes.rb
Rails.application.routes.draw do
  get '/index' => 'dashboard#index'
  resources :orders
  resources :products
  resources :suppliers
  resources :categories
  resources :brands

  get '/reports/order_supplier_report' => 'reports#order_supplier_report'

  get '/reports/product_order_report' => 'reports#product_order_report'

  get '/reports/product_brand_report' => 'reports#product_brand_report'

  get '/reports' => 'reports#index'

  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
  
  validates :name, presence: true, uniqueness: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: %i[ show edit update destroy ]

  include AjaxModalRails::Controller

  def index
    @brands = Brand.all
  end

  def show
  end

  def new
    @brand = Brand.new
  end

  def edit
  end

  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to brands_url, notice: "Marca adicionada com sucesso." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to brands_url, notice: "Marca atualizada com sucesso." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    begin
      @brand.destroy

      respond_to do |format|
        format.html { redirect_to brands_url, notice: "Marca removida com sucesso." }
      end
    rescue ActiveRecord::InvalidForeignKey => e
      respond_to do |format|
        format.html { redirect_to brands_url, alert: "Não é possível remover uma marca que está sendo utilizada em um produto." }
      end
    end
  end

  private
    def set_brand
      @brand = Brand.find(params[:id])
    end

    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.haml
= simple_form_for @brand, data: {submits_to_ajax_modal: true} do |f|
  .form-group
    = f.input :name, label: 'Nome', input_html: { class: 'form-control' }
  .actions
    = f.button :submit, "Salvar", class: 'btn btn-primary'

app/views/brands/edit.html.haml
%h1 Editar Marca
= render 'form', brand: @brand

app/views/brands/index.html.haml
.table-container
  .table-information
    %h1.table-title Marcas
    .table-actions
      = link_to 'Adicionar marca', new_brand_path, class: "new-button btn btn-success text-light", data: {loads_in_ajax_modal: true}
  .table-responsive
    %table.table.table-hover
      %thead
        %tr
          %th.col-2 ID
          %th.col-2 Nome
          %th.col-1 Ações
      %tbody
        - @brands.each do |brand|
          %tr
            %td= brand.id
            %td= brand.name  
            %td 
              .actions
                = link_to 'Editar', edit_brand_path(brand), class: "btn btn-warning text-light", data: {loads_in_ajax_modal: true}
                = link_to 'Apagar', brand, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-danger text-light"

app/views/brands/new.html.haml
%h1 Adicionar Marca
= render 'form', brand: @brand

app/views/brands/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @brand.name
= link_to 'Edit', edit_brand_path(@brand)
|
= link_to 'Back', brands_path